services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:cal@db:5432/postgres
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cal
      POSTGRES_DB: postgres
      TZ: America/Los_Angeles
      PGTZ: America/Los_Angeles
    volumes:
      - spaces_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  spaces_db: